- hosts: master
  become: yes
  tasks:

    # specify IP range
    - name: initialize the cluster
      shell: kubeadm init --apiserver-advertise-address={{ ansible_eth0.ipv4.address }} --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

      #create .kube directory
    - name: create .kube directory
      become: yes
      become_user: ahmed
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    # copy config to allow connection to whole k8s cluster
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ahmed/.kube/config
        remote_src: yes
        owner: ahmed

    # using flannel
    - name: install Pod network
      become: yes
      become_user: ahmed
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt


      #  sudo chown $(id -u):$(id -g) /home/ahmed/.kube/config