- hosts: all
  become: yes
  tasks:
    - name: create the 'ahmed' user
      user: name=ahmed append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ahmed' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ahmed ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ahmed user
      authorized_key: user=ahmed key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub